image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
build_script:
  - cmd: dotnet --info && dotnet build ./src/Tests/CacheManager.Serialization.Hyperion.Tests/CacheManager.Serialization.Hyperion.Tests.csproj -c Release
test_script:
  - cmd: dotnet test ./src/Tests/CacheManager.Serialization.Hyperion.Tests -c Release --test-adapter-path:. --logger:Appveyor 
deploy: off